### ISSUE TITLE
How to use your winding current to calculate motor torque

### ISSUE THREAD

**Issue by 76328** [HebiRobotics/hebi-matlab-examples#103]
I know the torque of your motor has some relationship of three phase winding currents
but the API only feedback one phase winding currents，so which phase dose it represent，and how to use it to calculate motor torque，and i want to use motor torque to do some control strategies

**Comment by ennerf** [comment]
This touches internal firmware details, so we prefer to not discuss it in public issues. However, please feel free to reach out to us directly at support@hebirobotics.com
